FROM node:18-slim

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN npm install

RUN pip3 install --break-system-packages -r services/analytics-service/requirements.txt

ENV DB_PATH=/shared/db/development.sqlite

CMD ["sh"]